### ISSUE TITLE
Feature tweak request: Hover/Tooltip delay

### ISSUE THREAD

**Issue by orkaboy** [drewg13/foundryvtt-band-of-blades#15]
One thing that my players complained about was that the tooltip hover (for example, hove a trait on an actor sheet, hover "Doctor" to figure out what it does etc) is a little too long. It takes about ~1.5s to appear on hover, which feels a little sluggish. It probably shouldn't be instant (may clutter screen), but if the delay could be reduced to 0.5s it would feel a lot more responsive.

This would apply to anything that has a tooltip-on-hover.

Not knowing how this is implemented, I don't know if this is something that could be changed in the game system, or if it requires changes to core Foundry.

**Comment by drewg13** [comment]
This is a CSS thing I Frankensteined into the system.  For better or worse, V10 will have a built-in tooltip function that I will switch over to using when I start working on supporting that.  The key benefit is that the system tooltips aren't constrained by the bounds of the parent Application, so I wouldn't need to micromanage the direction in which they appear to avoid having chunks cut off.  And the triggering code is simple and short.  I have a V10 system in the works, so the transition time to support that should be relatively short.

Initially, the intent was that the trigger needed to be a deliberate action.  I didn't want tooltips popping up all over the place during normal use.  But perhaps I took that a bit too far.  It's currently set to 1.2s, so your estimate was quite close.  Easy fix though.  I also changed the transition easing function, which may help make it feel more responsive.  Fixed in next version.
