### ISSUE TITLE
Rookies not visible to Marshal

### ISSUE THREAD

**Issue by orkaboy** [drewg13/foundryvtt-band-of-blades#2]
I have manually added rookies and soldiers and assigned them squad items. However, when I go to the Marshal Role sheet, I can not see the characters listed under the Squads tab. The specialists show up correctly under their tab.

If I press the "populate with fresh rookies" button, it creates a bunch of dummy sheets which *do* appear in the list correctly. They have the exact same squad resource as the ones I manually added so I don't know why this works, but they appear correctly on the Marshal's sheet.

Is there a way for me to make my already completed actors (+25 actors, some with skills filled in, all with custom art/names etc) appear correctly in the Marshal's list? Porting my game over from roll20 to Foundry, and kind of wished I knew I had to do things in this order from the start...

I created custom squads for my game and removed the compendium ones if this makes a difference (the correct squads are listed on the marshal's sheet, just none of the rookies/soldiers).

**Comment by drewg13** [comment]
Wow, it's been a while since I touched this code.  I see what you mean and it's an easy fix.  Your custom squad probably does not have the Active Effect needed to transfer to the Actor.  It's easiest to model after the stock ones included in the compendiums, but you may have removed those.  I don't recommend editing the compendiums directly, as you'll lose all your edits every single time you update the system, FYI.  So, first open your custom squad Item, click to create a new Active Effect, then edit the AE:
![image](https://user-images.githubusercontent.com/1455026/170395615-a06ededb-8b98-45d1-baa0-a37ea01b7435.png)

You can change the label and icon, but the only one who sees this is the GM.  Make sure the "transfer effect..." box is checked and click through to the Effects tab:
![image](https://user-images.githubusercontent.com/1455026/170395826-e3450486-19a3-4d8b-831d-695b6e9a4a6d.png)

In the Effects tab, click the plus icon to create a new Effect.  In the Attribute Key field, enter `data.squad`.  Change the Change Mode dropdown to Override.  In the Effect Value field, enter the name of your custom squad, exactly the same as the name of the squad Item.
![image](https://user-images.githubusercontent.com/1455026/170396165-90622540-b10e-41ad-a184-3a7c634b3442.png)

Now Submit Changes and close out of the Item sheet.  Open your rookie Actor sheets and re-add the custom squad Item.  They should now show up on the Marshal sheet properly.  There's probably a better way of doing this, but this is the Foundry-approved way to make changes to Actors based on the Items they hold.  Let me know if that works.  I'll tackle some of your other reported issues over the next few days.  Thanks for reporting them.

**Comment by orkaboy** [comment]
That worked! I had added the passive effect according to the same pattern (but not understanding what it was supposed to do, neglecting to add the attribute override). My squads function correctly now, thanks!

**Comment by orkaboy** [comment]
> I'll tackle some of your other reported issues over the next few days. Thanks for reporting them.

No worries! I don't want to come across as too critical since I think you've done a very good job here; I'd say the sheets are on par with the roll20 ones I'm used to and in some aspects it far surpasses them. For example: the pre-made compendium, the features that allows automatic added dice thanks to heritage traits, the direct connection between character sheets and the Marshal's sheet.

There's probably one or two things I think the roll20 ones do slightly better, but that might just be a thing to get used to. Specifically how the loadout is handled; the roll20 sheets are a little easier to track what items you have on you (the list is more compact, and you can see the entire loadout for your class listed, and it's easy to add custom items if need be). For everything else I think your sheets seem to be the better ones!
