### ISSUE TITLE
Visual: Playbook XP tooltip 

### ISSUE THREAD

**Issue by orkaboy** [drewg13/foundryvtt-band-of-blades#26]
It appears the Playbook XP tooltip is a bit broken. The tooltip is readable when hovering the pips, but if hovering the text, the following is rendered:
![image](https://user-images.githubusercontent.com/1805679/173437441-7e2b61d9-02a4-4e11-accf-f5430c22a117.png)

**Comment by drewg13** [comment]
Yeah, this is a limitation of my implementation of the tooltip code that I usually get around by positioning the tooltip more carefully.  This may have come about due to some reconfiguring of the sheet changing the relative positioning of the elements.  had to move where the tooltip text was in the element hierarchy.  Fixed in next release, but the V10 native tooltip code is much better when I move to that.
