### ISSUE TITLE
Feature request: Show (correct) XP triggers somewhere

### ISSUE THREAD

**Issue by orkaboy** [drewg13/foundryvtt-band-of-blades#27]
Currently, there are issues with the XP triggers text on the sheets.

- The only places to view the XP triggers are if hovering the class (upper right) or hovering the playbook text, which is unintuitive.
- The lists are not clear on where one entry starts and another begins.
- The lists appear to have the wrong entries (Vice -> copied from Blades in the Dark?) The correct list is on page 56 of the rulebook.

Suggestion: Put these as a regular bulletpoint list (with the one for the playbook injected dynamically) under a tab of its own (Advancement?), or maybe under Notes?

If you do make a new tab for it, maybe put the information about advancement caps (page 57) there as well.

**Comment by drewg13** [comment]
>The only places to view the XP triggers are if hovering the class (upper right) or hovering the playbook text, which is unintuitive.

Strong disagree.  The design intent here is not (and never has been) to be able to "teach" players how to play the game using sheets alone, it's strictly to refresh people's memories for the most important details.  Actually, I was requested to explicitly avoid anyone being able to play the game only using the sheets and without the book, so I made a series of judgement calls on where that boundary was.  I think they're fine where they are and certainly don't need special dedicated space.

Breaking up the list is not a bad suggestion, but more whitespace increases the size of the tooltip beyond what I'd like and any HTML tags get stripped out by Foundry.

You're correct that some of the text is copied over from Scum and Villainy though, so that will be corrected in next release.

**Comment by orkaboy** [comment]
Would the tooltip improve with V10 tooltips (allowed to be bigger/better formatted)?

My argument that this particular feature should still be available on the sheets (in a manner that doesn't make the game playable entirely without the book) is that this information is available on the official sheets provided by the publisher of the game for free: https://www.evilhat.com/home/band-of-blades-resources/
![image](https://user-images.githubusercontent.com/1805679/173493336-1bdc82ea-dae0-4c3a-9cfb-b7b717610fea.png)

I'll respect your judgement on the matter, however.

**Comment by orkaboy** [comment]
Reviewing the 1.8.1 sheets, what is there is probably fine.
