### ISSUE TITLE
Selecting a cargo type

### ISSUE THREAD

**Issue by pplurueda** [drewg13/foundryvtt-band-of-blades#40]
When selecting a cargo type, is it supposed to be automatically equipped with the appropriate objects?
It doesn't happen to me...

**Comment by drewg13** [comment]
Since "cargo type" isn't a term used in my system or in the rulebook, it's not totally clear what you mean.   If you mean Load, no, there is no automation there as there are choices that have to be made for some of the items, like the Officer's Normal Load Fine Shield OR Fine Pistol and Ammo.  It *does* restrict what items are visible in the Add Item dialog and you can multi-select the ones you want to add in order to add them all at once.  I tried to include automation where it made sense and could be done relatively simply, but there were some things that were more complex than I wanted to take on.
