### ISSUE TITLE
Feature request: Effect levels

### ISSUE THREAD

**Issue by orkaboy** [drewg13/foundryvtt-band-of-blades#6]
Currently, these effect levels appear when making rolls: **Limited**, **Standard** and **Great**.

However, when making judgement calls based on the situation and factoring in scale/potency differences, the GM might rule that the effect should be **Zero** or **Extreme** effect (see the section on Scale page 30-31 in the rulebook).

**Comment by drewg13** [comment]
This makes sense and is probably the sort of thing that would have come out in play, had it been extensively play-tested.  I will point out that Zero Effect is more of a GM gambit to draw out further resources and/or bargaining from the player leading to further negotiated changes to Position and Effect, because if left at Zero, there's no point in rolling anything anyway.  I'm not clear on what the mechanical effects of Extreme Effect would be though.  I could add something in, but I would be free-styling without more guidance from the book.

**Comment by orkaboy** [comment]
I don't have an exact ref from the book, but at least in Blades in the Dark, the typical clock effects are:

- Zero: nothing
- Limited: one tick
- Standard: two ticks
- Great: three ticks
- Extreme: five ticks

Beyond that would be freestyling. But the Extreme effect for example is what you'd get if you got a crit on a Great in regular play (actually starting out with Extreme usually requires a really good fictional position and a lot of resource spending, but it's not impossible by the mechanics of the game). The crit mechanic might make a very desperate (or stubborn) PC make a roll on Zero effect as well.

**Comment by drewg13** [comment]
The roll code is a spaghetti-code mess inherited from the Blades system and exacerbated by my fumblings, so it's not clear to me how this would effect the ultimate roll chat cards.  I've got partial support in there and I'll wait on your feedback.

**Comment by orkaboy** [comment]
So far it seems to be working good. All I really wanted was the ability to select those effect levels when making the roll, and that appears to be in there as requested.
