### ISSUE TITLE
Custom Art in Compendium

### ISSUE THREAD

**Issue by orkaboy** [drewg13/foundryvtt-band-of-blades#9]
Hi again. I wanted to add custom art/tokens to my undead, so I made a duplicate of the Undead Armies compendium in order to customize it. However, if I pick a minion (say, Bhed the Wolf) and add a custom image/prototype token, both revert to the grasping hand when I pull them from the compendium into a scene.

I ended up making actors in my game instead for all the undead and customizing them (something I hear isn't good to do in Foundry for performance reasons). I tested making a new compendium entirely and copying in my fancy tokens, and upon being added to the compendium, they revert to the default art.

I don't think this is a Foundry bug, I think it's something with how the Minion Actors are set up (some on-copy script?), but I could be wrong. My ideal situation is if I could have a compendium with all my Undead (with my custom art/tokens) that can be pulled into the game on demand, and removed to keep performance smooth.

**Comment by drewg13** [comment]
I need to copy over the PC script that accounts for custom art, that should be simple enough. 

In game actors causing performance issues shouldn't be a problem for you. What's happening there is, on connection, all in world assets are transferred to each person. Unless you're attaching huge custom art files or holding thousands of actors in world, it should be fine. It mostly comes up when people load up dnd5e and want to import their entire dndbeyond library in world at once, like some kind of digital hoarder.  Or when people run very long campaigns and never get rid of anything.  It would be an unusual BitD game that had enough Actors in world to cause performance issues in this way, especially since most items are kept and used in compendiums.

The way my system is intended to work is, when you go to pull Actors or Items from a sheet trigger of some type, the system will pull all compendium things of the correct type, then all in world things of the correct type. If there are things with identical names in both places, it presents the in world version over the compendium version under the assumption that the GM has imported and customized the in world version. So it should just be a matter of importing the thing closest to what you want and adding your customizations, which should then be the version presented automatically. If everything is working properly. 

That said, I'll try to get this particular issue fixed tonight or tomorrow and we can see where that leaves you on what you're attempting.

**Comment by drewg13** [comment]
An even easier fix than I thought, should be in the next version.  I never considered the use-case of user-configured assets in world compendiums.

**Comment by orkaboy** [comment]
> An even easier fix than I thought, should be in the next version. I never considered the use-case of user-configured assets in world compendiums.

Since I'm porting my game from roll20 mid-campaign, I already have art assets prepared for most the stuff I want to use. The BoB compendium, while very nice mechanically, unfortunately doesn't give much variety in terms of visuals.

**Comment by drewg13** [comment]
Right, I got permission from Stras to build the system, given open source and no monetization, but not to include any of the book art. I assume there are contractual limitations.   And I personally have no skill in that area.  My best effort was finding relevant free icons.

**Comment by orkaboy** [comment]
Perfectly understandable approach.
